### ISSUE TITLE
kubectl ket provider doesn't show the kubernetes provider config

### ISSUE THREAD

**Issue by jonnylangefeld** [crossplane-contrib/provider-kubernetes#11]
For the default crossplane providers you can see the provider configs via 
```
kubectl get provider
```
The kubernetes provider doesn't show up in that list as of know.

That's because in the CRD the `categories` section of the `providerconfigs.kubernetes.crossplane.io` crd is missing:
```
  names:
    categories:
    - crossplane
    - provider
```
This probably has to be generated through some kubebuilder annotations.

**Comment by haarchri** [comment]
@turkenh  fixed by https://github.com/crossplane-contrib/provider-kubernetes/pull/22 - you close the issue

**Comment by bretagne-peiqi** [comment]
seems not yet fixed, I use kubectl get provider/ providerconfig and it hanging

**Comment by johnkeates** [comment]
Not fixed here either, no ProviderConfig CRD available when installing Crossplane 0.24.x.
